FROM ubuntu:22.04

# install required packages
RUN DEBIAN_FRONTEND=noninteractive \
  apt-get update && apt-get install \
  -y wget make cppcheck gcc-arm-none-eabi git

RUN useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo -u 1001 ubuntu

USER ubuntu

WORKDIR /home/ubuntu
