on: [push]
jobs:
  build_and_static_analysis:
    runs-on: ubuntu-latest
    container:
      image luisjongind/arm_none_eabi_ubuntu2204:latest
    steps:
      - name: Check repository
        uses: actions/checkout@v3
      - run: make all
      - run: make static_analysis
